spring:
  cloud:
    function:
      definition: messageConsumer
    stream:
      bindings:
        messageConsumer-in-0:
          destination: message
          content-type: application/json
          group: message-consumers
      kafka:
        binder:
          brokers: ${BROKERS}
          auto-create-topics: true
          consumer-properties:
            auto.offset.reset: earliest