name: Deploy Dockerhub

on:
  push:
    branches: ["main"]

jobs:
  upload-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/modulo3:latest .

      - name: Deploy Dockerhub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/modulo3:latest
